"""
HTML Table Utility Functions

These utilities parse HTML tables generated by PaddleOCR-VL.

Responsibilities
----------------
- Parse PaddleOCR table HTML.
- Preserve rowspan.
- Preserve colspan.
- Preserve cell order.
- Preserve image references.
- Build a logical rectangular grid.
- Track merged-cell information.

No PaddleOCR inference logic belongs here.
No Excel/OpenPyXL logic belongs here.

The output of this module can be consumed by:
    - Excel exporter
    - CSV exporter
    - API exporter
    - Database exporter
"""

from __future__ import annotations

import itertools
import re

from dataclasses import dataclass, field
from html.parser import HTMLParser
from html import unescape
from pathlib import Path
from typing import Optional


# ============================================================================
# DATA MODELS
# ============================================================================


@dataclass
class TableCell:
    """
    Represents one HTML table cell.

    Parameters
    ----------
    value:
        Text content of the cell.

    row:
        Zero-based logical row.

    column:
        Zero-based logical column.

    rowspan:
        Number of rows occupied by the cell.

    colspan:
        Number of columns occupied by the cell.

    images:
        Image references found inside the cell.

    tag:
        HTML tag: td or th.
    """

    value: str

    row: int
    column: int

    rowspan: int = 1
    colspan: int = 1

    images: list[str] = field(default_factory=list)

    tag: str = "td"

    @property
    def is_merged(self) -> bool:
        """Return True when the cell spans multiple rows or columns."""

        return self.rowspan > 1 or self.colspan > 1

    @property
    def end_row(self) -> int:
        """Return the last logical row occupied by this cell."""

        return self.row + self.rowspan - 1

    @property
    def end_column(self) -> int:
        """Return the last logical column occupied by this cell."""

        return self.column + self.colspan - 1


@dataclass
class StructuredTable:
    """
    Structured representation of a PaddleOCR HTML table.
    """

    cells: list[TableCell] = field(default_factory=list)

    rows: list[list[Optional[TableCell]]] = field(
        default_factory=list
    )

    row_count: int = 0

    column_count: int = 0

    source_html: str = ""

    @property
    def merged_cells(self) -> list[TableCell]:
        """
        Return cells that contain rowspan/colspan.
        """

        return [
            cell
            for cell in self.cells
            if cell.is_merged
        ]

    @property
    def headers(self) -> list[str]:
        """
        Return the first logical row as text.
        """

        if not self.rows:
            return []

        return [
            cell.value if cell else ""
            for cell in self.rows[0]
        ]

    def to_matrix(self) -> list[list[str]]:
        """
        Convert the logical table into a normal text matrix.

        Important:
        This expands merged cells for data-processing purposes.

        It does NOT destroy the original merge information because
        self.cells still contains the rowspan/colspan metadata.
        """

        matrix = []

        for row in self.rows:

            matrix_row = []

            for cell in row:

                if cell is None:
                    matrix_row.append("")
                else:
                    matrix_row.append(cell.value)

            matrix.append(matrix_row)

        return matrix


# ============================================================================
# INTERNAL HTML PARSER
# ============================================================================


class _PaddleTableParser(HTMLParser):
    """
    Internal HTML parser.

    Parses one PaddleOCR-generated HTML table.
    """

    def __init__(self):

        super().__init__(
            convert_charrefs=True
        )

        self.rows: list[list[dict]] = []

        self.current_row: Optional[list[dict]] = None

        self.current_cell: Optional[dict] = None

        self.in_table = False

        self.in_cell = False

        self.in_image = False

        self.text_parts: list[str] = []

    # ------------------------------------------------------------------
    # START TAG
    # ------------------------------------------------------------------

    def handle_starttag(
        self,
        tag: str,
        attrs,
    ):

        tag = tag.lower()

        attributes = {
            key.lower(): value
            for key, value in attrs
        }

        # --------------------------------------------------------------
        # TABLE
        # --------------------------------------------------------------

        if tag == "table":

            self.in_table = True

            return

        # --------------------------------------------------------------
        # ROW
        # --------------------------------------------------------------

        if tag == "tr":

            if self.current_row is not None:
                self._finish_row()

            self.current_row = []

            return

        # --------------------------------------------------------------
        # CELL
        # --------------------------------------------------------------

        if tag in {"td", "th"}:

            if self.current_row is None:
                self.current_row = []

            self.current_cell = {
                "tag": tag,
                "rowspan": self._safe_int(
                    attributes.get("rowspan"),
                    default=1,
                ),
                "colspan": self._safe_int(
                    attributes.get("colspan"),
                    default=1,
                ),
                "text_parts": [],
                "images": [],
            }

            self.text_parts = []

            self.in_cell = True

            return

        # --------------------------------------------------------------
        # IMAGE
        # --------------------------------------------------------------

        if tag == "img" and self.in_cell:

            src = (
                attributes.get("src")
                or attributes.get("data-src")
                or ""
            )

            if src:

                self.current_cell[
                    "images"
                ].append(src)

            self.in_image = True

            return

        # --------------------------------------------------------------
        # BR
        # --------------------------------------------------------------

        if tag == "br" and self.in_cell:

            self.text_parts.append("\n")

    # ------------------------------------------------------------------
    # END TAG
    # ------------------------------------------------------------------

    def handle_endtag(
        self,
        tag: str,
    ):

        tag = tag.lower()

        # --------------------------------------------------------------
        # CELL
        # --------------------------------------------------------------

        if tag in {"td", "th"}:

            self._finish_cell()

            return

        # --------------------------------------------------------------
        # ROW
        # --------------------------------------------------------------

        if tag == "tr":

            self._finish_row()

            return

        # --------------------------------------------------------------
        # TABLE
        # --------------------------------------------------------------

        if tag == "table":

            if self.current_row is not None:

                self._finish_row()

            self.in_table = False

    # ------------------------------------------------------------------
    # TEXT
    # ------------------------------------------------------------------

    def handle_data(
        self,
        data: str,
    ):

        if not self.in_cell:
            return

        if not data:
            return

        self.text_parts.append(data)

    # ------------------------------------------------------------------
    # CELL FINISH
    # ------------------------------------------------------------------

    def _finish_cell(self):

        if not self.current_cell:
            return

        text = "".join(
            self.text_parts
        )

        text = self._clean_text(text)

        self.current_cell[
            "text"
        ] = text

        self.current_cell[
            "images"
        ] = list(
            self.current_cell.get(
                "images",
                [],
            )
        )

        if self.current_row is None:

            self.current_row = []

        self.current_row.append(
            self.current_cell
        )

        self.current_cell = None

        self.text_parts = []

        self.in_cell = False

        self.in_image = False

    # ------------------------------------------------------------------
    # ROW FINISH
    # ------------------------------------------------------------------

    def _finish_row(self):

        if self.current_cell is not None:

            self._finish_cell()

        if self.current_row:

            self.rows.append(
                self.current_row
            )

        self.current_row = None

    # ------------------------------------------------------------------
    # HELPERS
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_int(
        value,
        default: int = 1,
    ) -> int:

        try:

            parsed = int(
                str(value).strip()
            )

            return max(
                parsed,
                1,
            )

        except (
            TypeError,
            ValueError,
        ):

            return default

    @staticmethod
    def _clean_text(
        text: str,
    ) -> str:

        text = unescape(text)

        # Normalize whitespace while preserving
        # intentional line breaks.
        lines = []

        for line in text.splitlines():

            cleaned = " ".join(
                line.split()
            )

            if cleaned:
                lines.append(cleaned)

        return "\n".join(lines)


# ============================================================================
# PUBLIC PARSING FUNCTIONS
# ============================================================================


def parse_html_table(
    html: str,
) -> StructuredTable:
    """
    Parse one PaddleOCR HTML table.

    Parameters
    ----------
    html:
        HTML returned in PaddleOCR's block_content.

    Returns
    -------
    StructuredTable
    """

    if not html or not html.strip():

        raise ValueError(
            "HTML table content is empty."
        )

    parser = _PaddleTableParser()

    parser.feed(html)

    parser.close()

    if not parser.rows:

        raise ValueError(
            "No table rows found in HTML."
        )

    rows = _repair_missing_image_cells(
        parser.rows
    )

    return _build_structured_table(
        rows,
        html,
    )


# ============================================================================
# MISSING IMAGE CELL REPAIR
#
# PaddleOCR-VL sometimes omits the leading "Image" <td> entirely for a
# row instead of emitting an empty one (which is what happens for a
# normal continuation row inside a rowspan group). When that happens,
# every later cell in that specific <tr> lands one logical column to
# the left of where it belongs, and downstream code (which always
# strips column 0 as "the Image column") ends up discarding the real
# Product Description text instead of an empty placeholder.
#
# This step detects that pattern per-row, before the logical grid is
# built, and repairs it by inserting a synthetic empty Image cell (or,
# when the Image and Product Description got merged into one <td>,
# by splitting that single cell back into Image / Product Description
# / Case Size).
# ============================================================================


_IMAGE_PLACEHOLDER_RE = re.compile(
    r"^\d{1,4}(\s*\[\w+\])?$|^\[\w+\]$"
)

_TRAILING_CASE_SIZE_RE = re.compile(
    r"^(.*\S)\s+(\d+\s*[xX]\s*\d+(?:\.\d+)?\s*(?:CL|ML|G|KG|LTR|L)\b)\s*$",
    re.IGNORECASE,
)


def _normalize_cell_text(cell: dict) -> str:

    text = cell.get("text", "") or ""

    # PaddleOCR-VL sometimes emits a literal two-character "\n"
    # escape sequence inside cell text (e.g. "80\n" as the four
    # characters 8, 0, backslash, n) instead of a real line break,
    # most often right before an <img> tag in the Image/EAN columns.
    # Treat it the same as real whitespace.
    text = text.replace("\\n", " ")

    return " ".join(text.split())


def _new_cell(
    text: str = "",
    images: Optional[list[str]] = None,
) -> dict:

    return {
        "tag": "td",
        "rowspan": 1,
        "colspan": 1,
        "text": text,
        "images": list(images or []),
    }


def _looks_like_image_column_value(cell: dict) -> bool:
    """
    Return True when a cell's content is plausible content for the
    leading "Image" column: a product/group number, a footnote tag
    such as "[F01]", an actual image, or nothing at all.
    """

    text = _normalize_cell_text(cell)

    if not text:
        return True

    if _IMAGE_PLACEHOLDER_RE.match(text):
        return True

    # An image with no accompanying free text is a normal Image cell
    # (e.g. a photo with no overlaid product number).
    if cell.get("images") and not any(
        char.isalpha() for char in text
    ):
        return True

    return False


def _repair_missing_image_cells(
    raw_rows: list[list[dict]],
) -> list[list[dict]]:
    """
    Repair rows whose leading "Image" cell was dropped entirely by
    PaddleOCR-VL instead of being emitted empty.

    Only applies to tables whose header row starts with an "Image"
    column, and never touches the header row itself.

    Two kinds of rows must NOT be touched even though their first
    cell is not itself image-like:

    - Section-banner rows such as ``<td colspan="11">FRESH</td>``,
      which are a single cell spanning the whole table width.
    - Continuation rows that sit underneath a real ``rowspan`` on a
      previous row's Image cell (e.g. a shared group number/footnote
      block). For those rows, column 0 is legitimately already
      occupied by the row above, exactly like a "Consumer Deal"
      rowspan group, so the row's own first cell is correctly its
      Product Description (or per-row photo), not a dropped cell.
    """

    if len(raw_rows) < 2:
        return raw_rows

    header_row = raw_rows[0]

    if not header_row:
        return raw_rows

    header_text = _normalize_cell_text(
        header_row[0]
    ).strip().lower()

    if header_text != "image":
        return raw_rows

    repaired_rows = [header_row]

    image_rowspan_remaining = 0

    for row in raw_rows[1:]:

        if not row:
            repaired_rows.append(row)
            continue

        # ------------------------------------------------------------
        # Section-banner row (one cell spanning the whole table).
        # ------------------------------------------------------------

        if len(row) == 1 and row[0].get("colspan", 1) > 1:
            repaired_rows.append(row)
            continue

        # ------------------------------------------------------------
        # Continuation row already covered by a previous row's Image
        # rowspan: its first cell is genuinely not an Image value.
        # ------------------------------------------------------------

        if image_rowspan_remaining > 0:
            image_rowspan_remaining -= 1
            repaired_rows.append(row)
            continue

        first_cell = row[0]

        image_rowspan_remaining = max(
            int(first_cell.get("rowspan", 1)) - 1,
            0,
        )

        if _looks_like_image_column_value(first_cell):
            repaired_rows.append(row)
            continue

        text = _normalize_cell_text(first_cell)

        if not any(char.isalpha() for char in text):
            # Doesn't look like a product description either;
            # leave it alone rather than guessing.
            repaired_rows.append(row)
            continue

        if not first_cell.get("images"):

            # The leading <td> was skipped entirely and this cell is
            # really the Product Description. Give it back an empty
            # Image placeholder.
            repaired_rows.append(
                _drop_duplicate_price_before_percentage(
                    [_new_cell()] + row
                )
            )
            continue

        # The Image and Product Description (and possibly Case Size)
        # were merged into a single <td>. Split them back apart.
        match = _TRAILING_CASE_SIZE_RE.match(text)

        if match:
            description_text, case_size_text = match.groups()
        else:
            description_text, case_size_text = text, ""

        replacement = [
            _new_cell(images=first_cell.get("images")),
            _new_cell(text=description_text),
        ]

        if case_size_text:
            replacement.append(
                _new_cell(text=case_size_text)
            )

        repaired_rows.append(
            _drop_duplicate_price_before_percentage(
                replacement + _merge_leading_orphan_digit_image(row[1:])
            )
        )

    return repaired_rows


def _merge_leading_orphan_digit_image(
    tail: list[dict],
) -> list[dict]:
    """
    Merge a bare digit cell immediately followed by a bare image cell,
    near the start of ``tail``, into one cell.

    Scoped narrowly to the cells right after a Product Description /
    Image split repair: on a row already known to be malformed, the
    EAN Barcode column (normally one cell such as
    ``<td>7<img .../></td>``) is sometimes split into two separate
    <td> elements, which would otherwise desynchronize every column
    after it (Prom WSP, Std RSP, Promo POR, ...). Only the first few
    cells are examined (Case Size / Midas Code / EAN Barcode)
    to avoid ever touching the price columns further right.
    """

    search_limit = min(len(tail) - 1, 3)

    for index in range(search_limit):

        first, second = tail[index], tail[index + 1]

        if first.get("images"):
            continue

        if not re.fullmatch(r"\d{1,2}", _normalize_cell_text(first)):
            continue

        if not second.get("images") or _normalize_cell_text(second):
            continue

        merged = _new_cell(
            text=_normalize_cell_text(first),
            images=second.get("images"),
        )

        return tail[:index] + [merged] + tail[index + 2 :]

    return tail


_PRICE_RE = re.compile(r"^[£$€]\d+(\.\d{2})?$")

_PERCENTAGE_RE = re.compile(r"^\d+(\.\d+)?%$")


def _drop_duplicate_price_before_percentage(
    row: list[dict],
) -> list[dict]:
    """
    Drop a stray duplicate price cell that PaddleOCR-VL sometimes
    hallucinates right after the real "Std RSP" value on a row that
    belongs to a "Consumer Deal" rowspan group.

    Pattern observed in the wild:

        ... Prom WSP | Std RSP | <duplicate of Std RSP> | Promo POR ...

    The duplicate cell does not correspond to anything printed on the
    page; the row's real Consumer Deal value is the merged rowspan
    cell inherited from the top of its group. Left in place, the
    duplicate shifts every following column (Promo POR, Leaflet, ...)
    one position to the right.
    """

    for index in range(len(row) - 2):

        current_text = _normalize_cell_text(row[index])
        next_text = _normalize_cell_text(row[index + 1])
        following_text = _normalize_cell_text(row[index + 2])

        if not current_text or current_text != next_text:
            continue

        if not _PRICE_RE.match(current_text):
            continue

        if row[index].get("images") or row[index + 1].get("images"):
            continue

        if not _PERCENTAGE_RE.match(following_text):
            continue

        return row[: index + 1] + row[index + 2 :]

    return row


# ============================================================================
# GRID BUILDER
# ============================================================================


def _build_structured_table(
    raw_rows: list[list[dict]],
    source_html: str,
) -> StructuredTable:
    """
    Convert raw HTML rows into a logical grid.

    This is the important part.

    It understands rowspan and colspan.

    Example:

        <td rowspan="3">$1.65</td>

    occupies:

        row 5
        row 6
        row 7

    Example:

        <td colspan="11">FRESH</td>

    occupies:

        columns 1 -> 11
    """

    table = StructuredTable(
        source_html=source_html
    )

    # grid[row][column] = TableCell
    grid: list[list[Optional[TableCell]]] = []

    def ensure_row(
        row_index: int,
    ):

        while len(grid) <= row_index:

            grid.append([])

    def ensure_column(
        row_index: int,
        column_index: int,
    ):

        ensure_row(row_index)

        while (
            len(grid[row_index])
            <= column_index
        ):

            grid[row_index].append(None)

    def find_next_free_column(
        row_index: int,
        start_column: int,
    ) -> int:

        ensure_row(row_index)

        column = start_column

        while True:

            ensure_column(
                row_index,
                column,
            )

            if grid[row_index][column] is None:
                return column

            column += 1

    # --------------------------------------------------------------
    # Process every HTML row
    # --------------------------------------------------------------

    for html_row_index, raw_cells in enumerate(
        raw_rows
    ):

        ensure_row(
            html_row_index
        )

        current_column = 0

        for raw_cell in raw_cells:

            # Find first available logical column.
            current_column = find_next_free_column(
                html_row_index,
                current_column,
            )

            rowspan = max(
                int(
                    raw_cell.get(
                        "rowspan",
                        1,
                    )
                ),
                1,
            )

            colspan = max(
                int(
                    raw_cell.get(
                        "colspan",
                        1,
                    )
                ),
                1,
            )

            cell = TableCell(
                value=raw_cell.get(
                    "text",
                    "",
                ),
                row=html_row_index,
                column=current_column,
                rowspan=rowspan,
                colspan=colspan,
                images=list(
                    raw_cell.get(
                        "images",
                        [],
                    )
                ),
                tag=raw_cell.get(
                    "tag",
                    "td",
                ),
            )

            table.cells.append(
                cell
            )

            # ------------------------------------------------------
            # Occupy every logical position
            # ------------------------------------------------------

            for row_offset in range(
                rowspan
            ):

                logical_row = (
                    html_row_index
                    + row_offset
                )

                ensure_row(
                    logical_row
                )

                for column_offset in range(
                    colspan
                ):

                    logical_column = (
                        current_column
                        + column_offset
                    )

                    ensure_column(
                        logical_row,
                        logical_column,
                    )

                    existing = grid[
                        logical_row
                    ][
                        logical_column
                    ]

                    if existing is not None:

                        raise ValueError(
                            "Invalid HTML table structure: "
                            f"cell overlap at "
                            f"row={logical_row}, "
                            f"column={logical_column}."
                        )

                    grid[
                        logical_row
                    ][
                        logical_column
                    ] = cell

            current_column += colspan

    # --------------------------------------------------------------
    # Normalize column widths
    # --------------------------------------------------------------

    column_count = max(
        (
            len(row)
            for row in grid
        ),
        default=0,
    )

    for row in grid:

        while len(row) < column_count:

            row.append(None)

    table.rows = grid

    table.row_count = len(grid)

    table.column_count = column_count

    return table


# ============================================================================
# CONVENIENCE FUNCTIONS
# ============================================================================


def get_table_matrix(
    html: str,
) -> list[list[str]]:
    """
    Return a simple text matrix.

    This is useful when a DataFrame is required.

    Important:
    rowspan/colspan are expanded in the returned matrix,
    but the original merge information remains available
    through parse_html_table().
    """

    table = parse_html_table(
        html
    )

    return table.to_matrix()


def get_table_cells(
    html: str,
) -> list[TableCell]:
    """
    Return all logical source cells.
    """

    table = parse_html_table(
        html
    )

    return table.cells


def get_merged_cells(
    html: str,
) -> list[TableCell]:
    """
    Return only cells with rowspan or colspan.
    """

    table = parse_html_table(
        html
    )

    return table.merged_cells


def get_table_dimensions(
    html: str,
) -> tuple[int, int]:
    """
    Return:

        (rows, columns)
    """

    table = parse_html_table(
        html
    )

    return (
        table.row_count,
        table.column_count,
    )

def remove_image_column(
    table: StructuredTable,
) -> StructuredTable:
    """
    Remove the first Image column from the table.

    The Image column may contain:
        - Product images
        - Group numbers such as 1, 2, 3, 4
        - Empty cells

    The column is removed from the logical table before
    the data is sent to Excel.

    Existing rowspan/colspan information is preserved.
    """

    # --------------------------------------------------------------
    # Check whether the first column is actually an Image column.
    # --------------------------------------------------------------

    if table.column_count == 0:
        return table

    header = ""

    if table.rows:
        first_cell = table.rows[0][0]

        if first_cell is not None:
            header = first_cell.value.strip().lower()

    # Check whether the first column contains images.
    first_column_has_images = any(
        cell.column == 0 and cell.images
        for cell in table.cells
    )

    # Only remove the column when it looks like an Image column.
    #
    # This prevents us from accidentally removing the first
    # column from tables that do not contain an Image column.
    if (
        header != "image"
        and not first_column_has_images
    ):
        return table

    # --------------------------------------------------------------
    # Remove / shift cells.
    # --------------------------------------------------------------

    new_cells = []

    for cell in table.cells:

        # ----------------------------------------------------------
        # Case 1:
        # Cell is completely inside the first column.
        #
        # Example:
        #
        # <td>1</td>
        #
        # Remove it.
        # ----------------------------------------------------------

        if (
            cell.column == 0
            and cell.colspan == 1
        ):
            continue

        # ----------------------------------------------------------
        # Case 2:
        # Cell starts in column 0 and spans multiple columns.
        #
        # Example:
        #
        # <td colspan="3">...</td>
        #
        # becomes colspan="2".
        # ----------------------------------------------------------

        if cell.column == 0:

            cell.colspan -= 1

            # If nothing remains, remove the cell.
            if cell.colspan <= 0:
                continue

            cell.column = 0

        # ----------------------------------------------------------
        # Case 3:
        # Cell is after the Image column.
        #
        # Shift it one column to the left.
        # ----------------------------------------------------------

        else:

            cell.column -= 1

        new_cells.append(cell)

    # --------------------------------------------------------------
    # Update cell collection.
    # --------------------------------------------------------------

    table.cells = new_cells

    # --------------------------------------------------------------
    # Rebuild logical grid.
    # --------------------------------------------------------------

    new_column_count = max(
        table.column_count - 1,
        0,
    )

    new_grid = [
        [None for _ in range(new_column_count)]
        for _ in range(table.row_count)
    ]

    for cell in table.cells:

        for row_index in range(
            cell.row,
            cell.end_row + 1,
        ):

            if row_index >= table.row_count:
                continue

            for column_index in range(
                cell.column,
                cell.end_column + 1,
            ):

                if column_index >= new_column_count:
                    continue

                new_grid[
                    row_index
                ][
                    column_index
                ] = cell

    table.rows = new_grid

    table.column_count = new_column_count

    return table


def _looks_like_case_size(value: str) -> bool:
    """
    Return True when a value looks like a product case-size value.

    Examples:
        15 x 90G
        15 x 99G
        20 x 90G
        25 x 100G
        10 x 4 x 30G
    """

    if not value:
        return False

    value = value.strip().upper()

    if " X " not in value:
        return False

    parts = [
        part.strip()
        for part in value.split(" X ")
    ]

    if len(parts) < 2:
        return False

    # At least the first components should contain digits.
    return any(
        any(char.isdigit() for char in part)
        for part in parts
    )


def _looks_like_midas_code(value: str) -> bool:
    """
    Return True when a value looks like a Midas code.

    Examples:
        M304095
        M304079
        M292372
    """

    if not value:
        return False

    value = value.strip().upper()

    if not value.startswith("M"):
        return False

    return (
        len(value) >= 2
        and value[1:].isdigit()
    )


def _looks_like_product_description(
    value: str,
) -> bool:
    """
    Return True when a value looks like a product description.

    This is intentionally lightweight.

    We mainly want to distinguish product descriptions
    from values such as case sizes and Midas codes.
    """

    if not value:
        return False

    value = value.strip()

    if not value:
        return False

    if _looks_like_case_size(value):
        return False

    if _looks_like_midas_code(value):
        return False

    # Product descriptions normally contain alphabetic
    # characters.
    return any(
        char.isalpha()
        for char in value
    )


def fix_shifted_rows(
    table: StructuredTable,
) -> StructuredTable:
    """
    Fix rows where removing the Image column exposes a
    one-column-right shift.

    Example:

        Before:
        [None, Product, Case, Midas, EAN, Prom, Std, Consumer, Promo, Leaflet]

        After:
        [Product, Case, Midas, EAN, Prom, Std, Consumer, Promo, Leaflet]

    The entire row is shifted left.

    This is intentionally applied only when the row matches
    a strong structural signature.

    When a row contains rowspan cells (cells that span multiple rows),
    those cells' column coordinates are also decremented and the
    affected positions in all spanned rows are patched accordingly.
    """

    if table.column_count < 5:
        return table

    shifted_rows = []

    for row_index in range(table.row_count):

        row = table.rows[row_index]

        if len(row) < 5:
            continue

        # ----------------------------------------------------------
        # Read values from the current logical row.
        # ----------------------------------------------------------

        values = [
            cell.value.strip()
            if cell is not None and cell.value
            else ""
            for cell in row
        ]

        # ----------------------------------------------------------
        # We expect:
        #
        #   col 0 = empty
        #   col 1 = product description
        #   col 2 = case size
        #   col 3 = Midas code
        #
        # This is the signature created by the Image column.
        # ----------------------------------------------------------

        if values[0] != "":
            continue

        if not _looks_like_product_description(
            values[1]
        ):
            continue

        if not _looks_like_case_size(
            values[2]
        ):
            continue

        if not _looks_like_midas_code(
            values[3]
        ):
            continue

        shifted_rows.append(row_index)

    if not shifted_rows:
        return table

    print(
        "\n"
        + "=" * 80
    )

    print(
        "SHIFTED ROW CORRECTION"
    )

    print(
        "=" * 80
    )

    for row_index in shifted_rows:

        row = table.rows[row_index]

        print(
            f"Correcting row {row_index + 1}"
        )

        print(
            "Before:"
        )

        print(
            [
                cell.value
                if cell is not None
                else None
                for cell in row
            ]
        )

        # ----------------------------------------------------------
        # Shift the COMPLETE logical row left.
        # ----------------------------------------------------------

        shifted = (
            row[1:]
            + [None]
        )

        # Remove the leading empty cell from table.cells.
        empty_cell = row[0]
        if empty_cell is not None and empty_cell in table.cells:
            table.cells.remove(empty_cell)

        # ----------------------------------------------------------
        # Update cell column coordinates.
        #
        # For a cell whose anchor row matches the shifted row:
        #   - Always decrement its column by 1 (it genuinely moved).
        #   - If it also has rowspan > 1, patch every subsequent
        #     spanned row in the grid to reflect the new column.
        # ----------------------------------------------------------

        for col_idx, cell in enumerate(shifted):

            if cell is None:
                continue

            # Only process cells whose home row is this shifted row.
            if cell.row != row_index:
                continue

            old_col = cell.column
            new_col = col_idx
            cell.column = new_col

            # If the cell spans additional rows, fix those rows too.
            if cell.rowspan > 1:

                for spanned_row_index in range(
                    row_index + 1,
                    min(
                        row_index + cell.rowspan,
                        table.row_count,
                    ),
                ):

                    spanned_row = table.rows[
                        spanned_row_index
                    ]

                    if spanned_row is None:
                        continue

                    # Ensure the row list is long enough.
                    while len(spanned_row) <= max(
                        old_col, new_col
                    ):
                        spanned_row.append(None)

                    # Move the cell reference from old_col to new_col.
                    if (
                        old_col < len(spanned_row)
                        and spanned_row[old_col] is cell
                    ):
                        spanned_row[old_col] = None

                    if new_col < len(spanned_row):
                        spanned_row[new_col] = cell

        table.rows[row_index] = shifted

        print(
            "After:"
        )

        print(
            [
                cell.value
                if cell is not None
                else None
                for cell in shifted
            ]
        )

    # --------------------------------------------------------------
    # Normalize all row widths.
    # --------------------------------------------------------------

    _rebuild_table_grid(
        table
    )

    return table


def fix_shifted_merged_values(
    table: StructuredTable,
) -> StructuredTable:
    """
    Correct the displacement and rowspan mis-association between
    Std RSP and Consumer Deal.

    In the PDF, Consumer Deal is the merged cell (with a lower price/deal value),
    while Std RSP is a column of repeated higher standard retail prices.
    However, because the anchor row of a group was shifted right, the OCR engine
    often:
      1. Merged the Std RSP column values vertically and placed this merged cell
         in the Consumer Deal column (index 6, before/after shift adjustments).
      2. Placed the actual Consumer Deal value in index 7 (Promo POR) or similar
         as a single-row cell.

    This function detects when:
      - There is a rowspan cell 'A' (rowspan > 1) in STD_RSP_COL (index 5)
        after shifts have been corrected.
      - There is a single-row cell 'B' (rowspan == 1) in CONSUMER_DEAL_COL (index 6)
        on the same anchor row.
      - Both values look like prices/numbers.

    When this matches, we swap their roles:
      - We set A.rowspan = 1 (A is Std RSP for the anchor row).
      - We set B.rowspan = N (where N is A's original rowspan), making it the
        correct merged Consumer Deal cell.
      - We restore/retrieve Std RSP cells for all the spanned rows (rows R+1 to R+N-1)
        using existing cells from table.cells if they exist, or creating new ones
        with the same value as A.
    """
    if table.column_count < 7:
        return table

    STD_RSP_COL = 5
    CONSUMER_DEAL_COL = 6

    # Find all rowspan > 1 cells currently sitting in STD_RSP_COL.
    displaced_rowspan_cells = [
        cell
        for cell in table.cells
        if (
            cell.column == STD_RSP_COL
            and cell.rowspan > 1
        )
    ]

    if not displaced_rowspan_cells:
        return table

    any_changes = False

    for cell_A in displaced_rowspan_cells:
        anchor_row = cell_A.row
        N = cell_A.rowspan

        if anchor_row >= table.row_count:
            continue

        row = table.rows[anchor_row]
        if len(row) <= CONSUMER_DEAL_COL:
            continue

        cell_B = row[CONSUMER_DEAL_COL]
        if cell_B is None or cell_B.rowspan > 1:
            continue

        val_A = cell_A.value.strip() if cell_A.value else ""
        val_B = cell_B.value.strip() if cell_B.value else ""

        if not val_A or not val_B:
            continue

        # Let's verify they look like money/price values (e.g. contain digits)
        def is_numeric_or_price(s):
            import re
            return bool(re.search(r'\d', s))

        if not is_numeric_or_price(val_A) or not is_numeric_or_price(val_B):
            continue

        print()
        print("=" * 80)
        print("UNTANGLING STD RSP & CONSUMER DEAL")
        print("=" * 80)
        print(f"Anchor Row  : {anchor_row + 1}")
        print(f"Cell A (Std RSP, was rowspan={N})       : {val_A!r}")
        print(f"Cell B (Consumer Deal, was rowspan=1) : {val_B!r}")

        # Swap their rowspan and role!
        cell_A.rowspan = 1
        cell_B.rowspan = N
        cell_B.column = CONSUMER_DEAL_COL

        # Make sure cell_B is in table.cells if it wasn't already.
        if cell_B not in table.cells:
            table.cells.append(cell_B)

        # Restore/Rebuild the grid for all spanned rows (anchor_row to anchor_row + N - 1)
        for r in range(anchor_row, min(anchor_row + N, table.row_count)):
            # Ensure row length in grid
            while len(table.rows[r]) <= CONSUMER_DEAL_COL:
                table.rows[r].append(None)

            # 1. Update the Consumer Deal column (index 6) to hold the merged cell B
            table.rows[r][CONSUMER_DEAL_COL] = cell_B

            # 2. Update the Std RSP column (index 5)
            if r == anchor_row:
                table.rows[r][STD_RSP_COL] = cell_A
            else:
                # Look for an existing cell at row r, column 5 in table.cells
                existing_cell = None
                for c in table.cells:
                    if c.row == r and c.column == STD_RSP_COL:
                        existing_cell = c
                        break

                if existing_cell is not None:
                    # Keep existing cell
                    table.rows[r][STD_RSP_COL] = existing_cell
                    existing_cell.rowspan = 1
                    existing_cell.colspan = 1
                else:
                    # Create a new cell with the same value as A
                    new_cell = TableCell(
                        value=cell_A.value,
                        row=r,
                        column=STD_RSP_COL,
                        rowspan=1,
                        colspan=1
                    )
                    table.cells.append(new_cell)
                    table.rows[r][STD_RSP_COL] = new_cell

        any_changes = True

    if any_changes:
        print("Grid rebuilt after untangling Std RSP and Consumer Deal.")
        _rebuild_table_grid(table)

    return table


def fix_consumer_deal_group_alignment(
    table: StructuredTable,
) -> StructuredTable:
    """
    Realign "Consumer Deal" merged cells to the row groups defined by
    the leading group-number column.

    Background
    ----------
    Some leaflets group several product rows together with a single
    group number in the first column, using a real HTML rowspan
    (e.g. ``<td rowspan="7">4</td>``). Each such group has exactly one
    Consumer Deal value attached to it.

    PaddleOCR-VL occasionally misjudges *where* the Consumer Deal
    merge boundary falls: it produces the right values but splits
    them across the wrong row ranges (e.g. a 3-row group's deal gets
    only 1 row while the next 9 rows share one over-extended cell,
    instead of 3 rows / 7 rows). Because the misplacement happens
    inside the OCR/table-recognition step itself, it lands in
    ``block_content`` before any of our post-processing runs.

    This function detects that specific pattern and repairs it:

    1. It trusts the group-number column's rowspans as ground truth
       for row boundaries (they are short digits/labels and rarely
       misread).
    2. It only acts when the Consumer Deal column has exactly as many
       merged cells as there are groups, and those cells do not
       already line up with the group boundaries. Any other shape is
       left untouched rather than guessed at.
    3. It reassigns each Consumer Deal text to the group whose product
       descriptions share the most keywords with it (e.g. a deal
       mentioning "DORITOS" and "PEPSI" is matched to the group whose
       products are Doritos/Pepsi lines). When no group has a
       keyword match, it falls back to keeping the existing left-to-
       right ordering and only corrects the row boundaries.
    """

    GROUP_COL = 0

    if table.column_count < 2 or table.row_count < 2:
        return table

    header_row = table.rows[0] if table.rows else []

    def header_tokens(index: int) -> set[str]:
        if index >= len(header_row) or header_row[index] is None:
            return set()
        value = header_row[index].value or ""
        return set(re.findall(r"[A-Z]+", value.upper()))

    desc_col = None
    deal_col = None

    for index in range(table.column_count):
        tokens = header_tokens(index)
        if {"PRODUCT", "DESCRIPTION"}.issubset(tokens):
            desc_col = index
        elif {"CONSUMER", "DEAL"}.issubset(tokens):
            deal_col = index

    if desc_col is None or deal_col is None:
        return table

    # ------------------------------------------------------------------
    # Ground-truth group boundaries, from real rowspans in the group column.
    # ------------------------------------------------------------------

    group_ranges = sorted(
        (cell.row, cell.end_row)
        for cell in table.cells
        if cell.column == GROUP_COL and cell.rowspan > 1
    )

    if len(group_ranges) < 2:
        return table

    deal_cells = sorted(
        (
            cell
            for cell in table.cells
            if cell.column == deal_col and cell.row > 0
        ),
        key=lambda cell: cell.row,
    )

    if len(deal_cells) != len(group_ranges):
        return table

    current_ranges = [(cell.row, cell.end_row) for cell in deal_cells]

    if current_ranges == group_ranges:
        return table

    # ------------------------------------------------------------------
    # Score every (deal cell -> group) pairing by shared keywords
    # between the deal text and that group's product descriptions.
    # ------------------------------------------------------------------

    def keywords(text: str) -> set[str]:
        return set(re.findall(r"[A-Z]{4,}", (text or "").upper()))

    def group_keywords(start_row: int, end_row: int) -> set[str]:
        words: set[str] = set()
        for row_index in range(start_row, end_row + 1):
            if row_index >= len(table.rows):
                continue
            row = table.rows[row_index]
            if desc_col >= len(row) or row[desc_col] is None:
                continue
            words |= keywords(row[desc_col].value)
        return words

    group_kw = [group_keywords(start, end) for start, end in group_ranges]
    deal_kw = [keywords(cell.value) for cell in deal_cells]

    best_permutation = None
    best_score = None

    for permutation in itertools.permutations(range(len(group_ranges))):

        keyword_score = sum(
            len(deal_kw[deal_index] & group_kw[group_index])
            for deal_index, group_index in enumerate(permutation)
        )

        positional_score = sum(
            max(
                0,
                min(deal_cells[deal_index].end_row, group_ranges[group_index][1])
                - max(deal_cells[deal_index].row, group_ranges[group_index][0])
                + 1,
            )
            for deal_index, group_index in enumerate(permutation)
        )

        score = (keyword_score, positional_score)

        if best_score is None or score > best_score:
            best_score = score
            best_permutation = permutation

    print()
    print("=" * 80)
    print("CONSUMER DEAL / GROUP ALIGNMENT CORRECTION")
    print("=" * 80)

    for deal_index, group_index in enumerate(best_permutation):

        cell = deal_cells[deal_index]
        start_row, end_row = group_ranges[group_index]

        print(
            f"'{cell.value}' : rows {cell.row + 1}-{cell.end_row + 1} "
            f"-> rows {start_row + 1}-{end_row + 1}"
        )

        cell.row = start_row
        cell.rowspan = end_row - start_row + 1

    _rebuild_column_grid(table, deal_col)

    return table


def _rebuild_column_grid(
    table: StructuredTable,
    column_index: int,
) -> None:
    """
    Rebuild one column of the logical grid from table.cells.

    Used after a cell's row/rowspan has been changed directly, so the
    grid reflects the new merge boundaries without disturbing any
    other column.
    """

    for row in table.rows:
        if column_index < len(row):
            row[column_index] = None

    for cell in table.cells:

        if cell.column != column_index:
            continue

        for row_index in range(cell.row, cell.end_row + 1):

            if row_index >= len(table.rows):
                continue

            row = table.rows[row_index]

            if column_index < len(row):
                row[column_index] = cell


def fix_shifted_ean_barcode_rows(
    table: StructuredTable,
) -> StructuredTable:
    """
    Detect and correct rows where a missing EAN Barcode cell in HTML
    causes all columns to the right of Midas Code to shift left by 1.

    Pattern:
      - Header contains 'EAN Barcode' (or similar) and 'Prom WSP', 'Std RSP'.
      - EAN Barcode column cell contains a short price-like string (e.g. starts
        with '£', '$' or matches a decimal price pattern).
      - Prom WSP column cell also contains a price-like string.
    """
    if table.row_count < 2 or table.column_count < 5:
        return table

    # Find column indices from header
    header_vals = [
        (cell.value.strip().lower() if cell and cell.value else "")
        for cell in table.rows[0]
    ]

    midas_col = -1
    ean_col = -1
    prom_col = -1
    std_col = -1

    for idx, val in enumerate(header_vals):
        if "midas" in val:
            midas_col = idx
        elif "barcode" in val or "ean" in val:
            ean_col = idx
        elif "prom" in val and "wsp" in val:
            prom_col = idx
        elif "std" in val and "rsp" in val:
            std_col = idx

    if ean_col == -1 or prom_col == -1 or std_col == -1:
        return table

    def is_price_like(s):
        """
        Return True only for a well-formed currency amount such as
        '£8.69' or '99p'.

        This intentionally does NOT match:
          - Bare digit sequences (e.g. '4002559020247'), which are
            EAN barcode digits that PaddleOCR sometimes transcribes
            as text alongside the barcode image.
          - Garbled OCR noise that merely starts with a currency
            symbol (e.g. "£5'000'112'66'96'88\""), which happens
            when the barcode image itself is misread as text.

        Matching either of those loosely used to make this function
        mistake a barcode cell for a genuinely shifted price and
        overwrite real Prom WSP / Std RSP values with barcode noise.
        """
        if not s:
            return False
        s = s.strip()
        if re.match(r'^[£$€]\d{1,4}(\.\d{2})?$', s):
            return True
        if re.match(r'^\d{1,3}(\.\d{2})?p$', s, re.IGNORECASE):
            return True
        return False

    for r in range(1, table.row_count):
        row = table.rows[r]
        if len(row) <= max(ean_col, prom_col, std_col):
            continue

        cell_ean = row[ean_col]
        cell_prom = row[prom_col]

        if cell_ean is not None and not cell_ean.images:
            val_ean = cell_ean.value.strip() if cell_ean.value else ""
            if is_price_like(val_ean):
                val_prom = cell_prom.value.strip() if cell_prom and cell_prom.value else ""

                if is_price_like(val_prom) and val_prom != val_ean:
                    print()
                    print("=" * 80)
                    print("SHIFTED EAN BARCODE ROW CORRECTION")
                    print("=" * 80)
                    print(f"Row {r + 1}:")
                    print(f"  EAN Cell (has WSP price) : {val_ean!r}")
                    print(f"  Prom Cell (has RSP price): {val_prom!r}")

                    # Check if std_col in the grid is occupied by a cell from a previous row
                    cell_prev = row[std_col]
                    if cell_prev is not None and cell_prev.row < r:
                        # Truncate its rowspan so it doesn't spill into this row
                        print(f"  Truncating rowspan cell {cell_prev.value!r} from row {cell_prev.row+1} (rowspan was {cell_prev.rowspan})")
                        cell_prev.rowspan = r - cell_prev.row

                    # Shift them to their correct columns!
                    cell_ean.column = prom_col
                    if cell_prom is not None:
                        cell_prom.column = std_col

                    row[ean_col] = None
                    row[prom_col] = cell_ean
                    row[std_col] = cell_prom

    _rebuild_table_grid(table)
    return table


def remove_barcode_column(
    table: StructuredTable,
) -> StructuredTable:
    """
    Find and remove the 'EAN Barcode' column entirely from the StructuredTable.
    """
    if table.row_count < 1 or table.column_count < 2:
        return table

    header_vals = [
        (cell.value.strip().lower() if cell and cell.value else "")
        for cell in table.rows[0]
    ]

    barcode_col_idx = -1
    for idx, val in enumerate(header_vals):
        if "barcode" in val or "ean" in val:
            barcode_col_idx = idx
            break

    if barcode_col_idx == -1:
        return table

    print(f"Removing EAN Barcode column at index {barcode_col_idx}...")

    # 1. Remove all cells belonging to this column from table.cells
    cells_to_remove = [c for c in table.cells if c.column == barcode_col_idx]
    for c in cells_to_remove:
        table.cells.remove(c)

    # 2. Decrement column coordinate for all cells to the right of EAN Barcode
    for c in table.cells:
        if c.column > barcode_col_idx:
            c.column -= 1

    # 3. Remove the column index element from all rows in the grid
    for r in range(table.row_count):
        row = table.rows[r]
        if barcode_col_idx < len(row):
            row.pop(barcode_col_idx)

    # 4. Decrement the table column count
    table.column_count -= 1

    # 5. Rebuild the table grid to keep everything consistent
    _rebuild_table_grid(table)

    return table




# ============================================================================
# HEADER-LESS TABLE FRAGMENTS
#
# PaddleOCR-VL sometimes splits one physical table into several
# separate <table> blocks (e.g. when a table continues after a page
# break, or a section banner interrupts it). The continuation
# fragment occasionally starts directly with a data row instead of
# repeating the column header row. Every downstream function in this
# module (select_output_columns, remove_barcode_column,
# fix_consumer_deal_group_alignment, ...) identifies columns by
# reading header keywords from row 0, so a fragment with no real
# header silently keeps the wrong columns (e.g. "Case Size" leaking
# into the final output) instead of being cleaned up.
#
# json_to_excel.py remembers the last real header it saw and, when a
# later table's row 0 doesn't look like a header at all, prepends
# that remembered header rather than guessing column meaning from
# data values.
# ============================================================================


_KNOWN_HEADER_TOKENS = {
    "IMAGE", "PRODUCT", "DESCRIPTION", "CASE", "SIZE", "MIDAS", "CODE",
    "EAN", "BARCODE", "PROM", "WSP", "STD", "RSP", "CONSUMER", "DEAL",
    "PROMO", "POR", "LEAFLET", "FEATURE", "SPACE",
}


def looks_like_real_header(table: StructuredTable) -> bool:
    """
    Return True when row 0 reads as an actual column-header row.

    Every non-empty cell's words must belong to the known set of
    header vocabulary (Product, Description, Midas, Code, Prom, WSP,
    ...). A row holding real product data - names, prices, case
    sizes, Midas codes - will almost always contain at least one word
    outside that vocabulary, so this stays conservative rather than
    merely checking for one or two keywords.
    """

    if not table.rows:
        return False

    header_row = table.rows[0]

    non_empty_cells = [
        cell
        for cell in header_row
        if cell is not None and cell.value and cell.value.strip()
    ]

    if not non_empty_cells:
        return False

    for cell in non_empty_cells:

        tokens = set(re.findall(r"[A-Z]+", cell.value.upper()))

        if not tokens or not tokens.issubset(_KNOWN_HEADER_TOKENS):
            return False

    return True


def get_header_labels(table: StructuredTable) -> list[str]:
    """
    Return row 0's cell values as plain strings, one per column.
    """

    if not table.rows:
        return []

    return [
        cell.value if cell is not None else ""
        for cell in table.rows[0]
    ]


def prepend_header_row(
    table: StructuredTable,
    header_labels: list[str],
) -> StructuredTable:
    """
    Insert ``header_labels`` as a new row 0, shifting every existing
    row down by one.

    Used only when a table fragment's row 0 is real product data
    (``looks_like_real_header`` returned False) and a previous table
    fragment with the same column count supplied a real header, so
    that column-keyword lookups downstream keep working.
    """

    if len(header_labels) != table.column_count:
        return table

    for cell in table.cells:
        cell.row += 1

    header_cells = [
        TableCell(value=label, row=0, column=index)
        for index, label in enumerate(header_labels)
    ]

    table.cells = header_cells + table.cells

    table.row_count += 1

    table.rows = [
        list(header_cells)
    ] + list(table.rows)

    return table


DEFAULT_OUTPUT_COLUMNS: list[tuple[str, list[str]]] = [
    ("Product Description", ["PRODUCT", "DESCRIPTION"]),
    ("Midas Code", ["MIDAS"]),
    ("Prom WSP", ["PROM", "WSP"]),
    ("Std RSP", ["STD", "RSP"]),
    ("Consumer Deal", ["CONSUMER", "DEAL"]),
    ("Promo POR", ["PROMO", "POR"]),
]


def select_output_columns(
    table: StructuredTable,
    column_specs: Optional[list[tuple[str, list[str]]]] = None,
) -> StructuredTable:
    """
    Keep only the requested output columns, in the given order.

    Columns are matched against the header row by whole-word keyword
    tokens (case-insensitive), e.g. "Prom WSP" requires both the
    "PROM" and "WSP" tokens. This means the function works regardless
    of which extra columns (group numbers, case size, EAN barcode,
    leaflet flags, ...) happen to be present in a given table, and
    "Prom WSP" is never confused with "Promo POR".

    When none of the requested columns can be matched in the header,
    the table is returned unchanged rather than silently emptied.
    """

    if column_specs is None:
        column_specs = DEFAULT_OUTPUT_COLUMNS

    if not table.rows or table.column_count == 0:
        return table

    header_row = table.rows[0]

    def header_tokens(cell) -> set[str]:
        if cell is None or not cell.value:
            return set()
        return set(re.findall(r"[A-Z]+", cell.value.upper()))

    matched_columns = []

    for _label, required_keywords in column_specs:

        required = {keyword.upper() for keyword in required_keywords}

        match_index = None

        for index, cell in enumerate(header_row):

            if required.issubset(header_tokens(cell)):
                match_index = index
                break

        if match_index is not None:
            matched_columns.append(match_index)

    if not matched_columns:
        return table

    new_table = StructuredTable(source_html=table.source_html)

    new_cells = []

    for new_index, old_index in enumerate(matched_columns):

        for cell in table.cells:

            if cell.column != old_index:
                continue

            new_cells.append(
                TableCell(
                    value=cell.value,
                    row=cell.row,
                    column=new_index,
                    rowspan=cell.rowspan,
                    colspan=1,
                    images=list(cell.images),
                    tag=cell.tag,
                )
            )

    new_table.cells = new_cells
    new_table.row_count = table.row_count
    new_table.column_count = len(matched_columns)

    new_table.rows = [
        [None for _ in range(new_table.column_count)]
        for _ in range(new_table.row_count)
    ]

    for cell in new_cells:
        for row_index in range(cell.row, cell.end_row + 1):
            if row_index >= new_table.row_count:
                continue
            new_table.rows[row_index][cell.column] = cell

    return new_table


def _rebuild_table_grid(
    table: StructuredTable,
) -> None:
    """
    Rebuild table.rows from the current logical grid.

    The current logical grid is authoritative after
    structural correction.
    """

    if not table.rows:
        return

    # Ensure every row has the expected width.
    for row_index, row in enumerate(
        table.rows
    ):

        if len(row) < table.column_count:

            table.rows[row_index] = (
                row
                + [None]
                * (
                    table.column_count
                    - len(row)
                )
            )

        elif len(row) > table.column_count:

            table.rows[row_index] = (
                row[
                    :table.column_count
                ]
            )


# ============================================================================
# DEBUG / MANUAL TEST
# ============================================================================


def print_table_structure(
    table: StructuredTable,
):
    """
    Print useful diagnostics for debugging.
    """

    print(
        "=" * 80
    )

    print(
        "HTML TABLE STRUCTURE"
    )

    print(
        "=" * 80
    )

    print(
        f"Rows    : {table.row_count}"
    )

    print(
        f"Columns : {table.column_count}"
    )

    print(
        f"Cells   : {len(table.cells)}"
    )

    print(
        f"Merged  : {len(table.merged_cells)}"
    )

    print(
        "=" * 80
    )

    for index, cell in enumerate(
        table.cells,
        start=1,
    ):

        print(
            f"Cell {index:03d}"
        )

        print(
            f"  Position : "
            f"row={cell.row + 1}, "
            f"column={cell.column + 1}"
        )

        print(
            f"  Span     : "
            f"rowspan={cell.rowspan}, "
            f"colspan={cell.colspan}"
        )

        print(
            f"  Value    : "
            f"{cell.value!r}"
        )

        if cell.images:

            print(
                f"  Images   : "
                f"{cell.images}"
            )

        print()


def print_table_grid(
    table: StructuredTable,
):
    """
    Print logical grid.
    """

    print(
        "=" * 80
    )

    print(
        "LOGICAL TABLE GRID"
    )

    print(
        "=" * 80
    )

    for row_index, row in enumerate(
        table.rows,
        start=1,
    ):

        values = []

        for cell in row:

            if cell is None:

                values.append("")

            else:

                values.append(
                    cell.value
                )

        print(
            f"ROW {row_index:02d}: "
            f"{values}"
        )


# ============================================================================
# MANUAL TEST
# ============================================================================


if __name__ == "__main__":

    print(
        "=" * 80
    )

    print(
        "HTML TABLE UTILS MANUAL TEST"
    )

    print(
        "=" * 80
    )

    # --------------------------------------------------------------
    # Small controlled test
    # --------------------------------------------------------------

    test_html = """
    <table>
        <tr>
            <td>Product</td>
            <td>Price</td>
            <td>Deal</td>
        </tr>

        <tr>
            <td>AERO MILK</td>
            <td>£1.65</td>
            <td rowspan="3">ANY 2 FOR £3</td>
        </tr>

        <tr>
            <td>AERO ORANGE</td>
            <td>£1.65</td>
        </tr>

        <tr>
            <td>AERO MINT</td>
            <td>£1.65</td>
        </tr>

        <tr>
            <td colspan="3">SOFT DRINKS</td>
        </tr>

        <tr>
            <td>Water</td>
            <td>£1.25</td>
            <td>34.4%</td>
        </tr>
    </table>
    """

    table = parse_html_table(
        test_html
    )

    print_table_structure(
        table
    )

    print_table_grid(
        table
    )

    print(
        "=" * 80
    )

    print(
        "MERGED CELLS"
    )

    print(
        "=" * 80
    )

    for cell in table.merged_cells:

        print(
            f"Value={cell.value!r} | "
            f"Start=({cell.row + 1}, "
            f"{cell.column + 1}) | "
            f"End=({cell.end_row + 1}, "
            f"{cell.end_column + 1}) | "
            f"rowspan={cell.rowspan} | "
            f"colspan={cell.colspan}"
        )

    print(
        "=" * 80
    )

    print(
        "TABLE MATRIX"
    )

    print(
        "=" * 80
    )

    for row in table.to_matrix():

        print(row)

    print(
        "=" * 80
    )

    print(
        "Manual test completed successfully."
    )

    print(
        "=" * 80
    )